### ISSUE TITLE
gzipped html file is not understood by all clients

### ISSUE THREAD

**Issue by mkel** [EvidentSolutions/gradle-gzjar-plugin#1]
If using gradle-gzjar-plugin to gzip index.html, 
https://developers.google.com/speed/pagespeed/insights/ complains
"Decoding the main resource failed. Please ensure that the page loads properly in a browser."

Also http://validator.w3.org/ fails with this html.

Page loads properly in browsers.

Pagespeed and w3 validator work if I let my environment do the gzip instead.

**Comment by komu** [comment]
Thanks, fixed in `0.1.2`.
